### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by viniciusban** [vmesel/PyJobs#187]
O PyJobs é um projeto com bastante coisa a ser implementada. Temos muitas coisas
que podemos mexer e melhorar no sistema! xD

Essa issue é atualizada com frequência.

## Previsão de coisas a serem feitas

 - [x] #196 Troca de front-end para poder permitir melhor UX e UI
 - [x] #186 #188 Atualizar para o Django 2.2
 - [x] #195 Melhorar responsividade do portal para podermos permitir aos usuários melhor atualização de formulários
  - [x] #194 Form de criação de vaga
  - [x] #193 Form de atualização de dados do usuário
  - [x] #192 Form de atualização de senha
 - [x] #191 Exterminar erros de code-smell reportados pelo CodeClimate
 - [x] #190 Arrumar lógicas da view de contato para remover a validação do RECAPTCHA da view e colocar no form
 - [x] #189 Adicionar campo de tipo de contratação (CLT, PJ, Freela, CLT ou PJ, A discutir)

**Comment by vmesel** [comment]
@viniciusban תודה (todah) my friend!
